version: 1.10.0.{build}
environment:
  TIMEOUT: "60m"
  DOCKER_REMOTE_DAEMON: "1"

install:
  - choco install -y mingw
  - choco install -y virtualbox
  - choco install -y docker-machine
  # http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm-gcc-5.1.0-3.exe/download

build_script:
  # build the daemon image
  - docker-machine.exe create -d virtualbox dev
  - ps: docker-machine.exe env dev --shell powershell | Invoke-Expression

# commithash=$(git rev-parse --short HEAD)
# docker.exe build --rm --force-rm -t "docker:$commithash" .
# docker.exe run -it --privileged -e GOMAXPROCS=1 --pid host -d --name "docker-$commithash" --net host "docker:$commithash" bash -c 'hack/make.sh binary && cp bundles/1.10.0-dev/binary/docker /bin/docker && exec docker daemon -D -H tcp://0.0.0.0:2375'
# Write-Host "Waiting for daemon in container to start"
# Sleep 30
# $env:DOCKER_TEST_HOST="$env:DOCKER_HOST"
# #unset DOCKER_CLIENTONLY
# # run tests
# #hack/make.sh binary test-integration-cli

artifacts:
  - path: '**\*.exe'
    name: Binary
